# Generated by Django 5.0.7 on 2024-07-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresponder",
            name="_output",
            field=models.TimeField(),
        ),
    ]
