# Generated by Django 5.0.7 on 2024-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_queryresponder__output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresponder",
            name="_output",
            field=models.TextField(),
        ),
    ]
